[package]
name = "l_data_types"
version = "0.1.0"
authors = ["SSJ <931605782@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
